version: '2.0'
services:
  nodewebhooker:
    container_name: nodewebhooker
    user: "${UID}:${GID}"
    build:
      context: ./
    command: node server.js
    ports:
      - ${WEBHOOK_PORT}:3000
    environment:
      NODE_ENV: production
      WEBHOOK_URL: ${WEBHOOK_URL}
      UID: ${WEBHOOK_UID}
      GID: ${WEBHOOK_GID}
      WEBHOOK_PORT: ${WEBHOOK_PORT}
# version: '3.5'
# services:
#   nodeawebhooker_devel:
#     container_name: nodeawebhooker_devel
#     image: mcr.microsoft.com/vscode/devcontainers/javascript-node:14
#     restart: unless-stopped
#     user: "${UID}:${GID}"
#     #  entrypoint: /usr/local/share/docker-init.sh
#     command: sleep infinity
#     volumes:
#       - /var/run/docker.sock:/var/run/docker-host.sock
#       - /share/Sync/projects/nodeawebhooker:/workspace:cached
#     ports:
#       - "3010:3000"
#     # environment:
#     #   - PHP_TZ="America/Chicago"

# # volumes:
# #   etc:

networks:
  default:
    external:
      name: services_bridge
