version: '2.0'
services:
  nodewebhooker:
    container_name: nodewebhooker
    user: "${UID}:${GID}"
    build:
      context: ./
    command: node server.js
    ports:
      - ${WEBHOOK_PORT}:3000
    environment:
      NODE_ENV: production
      WEBHOOK_URL: ${WEBHOOK_URL}
      UID: ${WEBHOOK_UID}
      GID: ${WEBHOOK_GID}
      WEBHOOK_PORT: ${WEBHOOK_PORT}
