# ARG user="nodeawebhooker"
FROM mhart/alpine-node:12


# RUN apk add openssh-client
# RUN useradd -m user
# RUN mkdir -p /home/user/.ssh
# COPY id_rsa_shared /home/user/.ssh/id_rsa
# RUN chown -R user:user /home/user/.ssh
# RUN echo "Host remotehost\n\tStrictHostKeyChecking no\n" >> /home/user/.ssh/config
# USER user
# CMD ["/bin/bash"]


# This stage installs our modules
WORKDIR /app
COPY package.json package-lock.json ./

# If you have native dependencies, you'll need extra tools
# RUN apk add --no-cache make gcc g++ python3
RUN apk add --no-cache openssh-client

RUN npm ci --prod

# Then we copy over the modules from above onto a `slim` image
FROM mhart/alpine-node:slim-12

# If possible, run your container using `docker run --init`
# Otherwise, you can use `tini`:
# RUN apk add --no-cache tini
# ENTRYPOINT ["/sbin/tini", "--"]

WORKDIR /app
COPY --from=0 /app .
COPY . .
CMD ["node", "index.js